pub const SOLEND_PROGRAM: &str = "ALend7Ketfx5bxh6ghsCDXAoDrhvEmsXT3cynB6aPLgx";
pub const DEVNET_SOLEND_LENDING_MARKET: &str = "GvjoVKNjBvQcFaSKUW1gTE7DxhSpjHbE69umVR5nPuQp";

pub const DEVNET_SOLEND_SOL_RESERVE: &str = "5VVLD7BQp8y3bTgyF5ezm1ResyMTR3PhYsT4iHFU8Sxz";
pub const DEVNET_SOLEND_USDC_RESERVE: &str = "FNNkz4RCQezSSS71rW2tvqZH1LCkTzaiG7Nd1LeA5x5y";
pub const DEVNET_SOLEND_USDT_RESERVE: &str = "ERm3jhg8J94hxr7KmhkRvnuYbKZgNFEL4hXzBMeb1rQ8";
pub const DEVNET_SOLEND_CSOL_COLLATERAL_MINT: &str = "FzwZWRMc3GCqjSrcpVX3ueJc6UpcV6iWWb7ZMsTXE3Gf";
pub const DEVNET_SOLEND_CSOL_LIQUIDITY_SUPPLY: &str = "furd3XUtjXZ2gRvSsoUts9A5m8cMJNqdsyR2Rt8vY9s";
